# -*- coding: utf-8 -*-
"""Sales-data-csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OW14uzoCBpR_6sk8_HqYRjVs10vyEC5C
"""

import pandas as pd
import numpy as np

np.random.seed(42)

n = 60

data = {
    "OrderID": range(1001, 1001+n),
    "Date": pd.date_range(start="2024-01-01", periods=n, freq="7D"),
    "CustomerID": np.random.randint(200, 250, n),
    "City": np.random.choice(["Lahore", "Karachi", "Islamabad"], n),
    "Category": np.random.choice(["Electronics", "Clothing", "Home Appliances"], n),
    "Product": np.random.choice(["Laptop", "Phone", "Shirt", "Shoes", "Microwave", "Tablet"], n),
    "Quantity": np.random.randint(1, 5, n),
    "Price": np.random.randint(50, 1000, n)
}

df = pd.DataFrame(data)

# Create Total Sales column
df["Total_Sales"] = df["Quantity"] * df["Price"]

df.to_csv("retail_sales_data.csv", index=False)

df.head()

import pandas as pd
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv("retail_sales_data.csv")

print("Dataset Shape:", df.shape)
print("\nFirst 5 Rows:")
print(df.head())

# Convert Date column
df["Date"] = pd.to_datetime(df["Date"])

# Basic Statistics
print("\nSummary Statistics:")
print(df.describe())

# Total Revenue
total_revenue = df["Total_Sales"].sum()
print("\nTotal Revenue:", total_revenue)

# Revenue by Category
category_sales = df.groupby("Category")["Total_Sales"].sum()
print("\nRevenue by Category:")
print(category_sales)

# Revenue by City
city_sales = df.groupby("City")["Total_Sales"].sum()
print("\nRevenue by City:")
print(city_sales)

# Monthly Revenue Trend
df["Month"] = df["Date"].dt.month
monthly_sales = df.groupby("Month")["Total_Sales"].sum()

print("\nMonthly Sales:")
print(monthly_sales)

# Top 5 Customers
top_customers = df.groupby("CustomerID")["Total_Sales"].sum().sort_values(ascending=False).head()
print("\nTop 5 Customers:")
print(top_customers)

# Visualization 1
category_sales.plot(kind="bar")
plt.title("Revenue by Category")
plt.ylabel("Total Sales")
plt.show()

# Visualization 2
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.ylabel("Total Sales")
plt.show()

# Correlation
correlation = df[["Quantity", "Price", "Total_Sales"]].corr()
print("\nCorrelation Matrix:")
print(correlation)

df.to_csv("cleaned_retail_sales.csv", index=False)

print("\nAnalysis Completed Successfully!")